
services:
  - type: web
    name: trading-sim-supabase-full
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASS
        sync: false
